Parameters:
  BucketNameParam:
    Type: String
    Default: swastik-personal-bucket
    Description: Bucket Name to be used
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: BucketNameParam
