---
  Resources:
    MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-02354e95b39ca8dec
        InstanceType: t2.micro
        KeyName: my-ubuntu
        SecurityGroups:
          - !Ref MySecurityGroup
        Tags:
          - Key: Name
            Value: MyEC2Instance

    MySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SkywalkerGroup
        GroupName: skywalker-group
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 8080
            ToPort: 8090
            CidrIp: 183.83.0.0/16
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 183.83.0.0/16
