---
  Resources:
    MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        AvailabilityZone: us-east-1a
        ImageId: ami-02354e95b39ca8dec
        InstanceType: t2.micro
        KeyName: my-ubuntu
        SecurityGroups:
          - !Ref MySecurityGroup
        Volumes:
          -
            VolumeId: !Ref MyVolume
            Device: /dev/sdf

    MyVolume:
      Type: AWS::EC2::Volume
      Properties:
        SnapshotId: snap-0b0b30ec14111c740
        Size: 5
        VolumeType: gp2
        AvailabilityZone: us-east-1a

    MySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: SkywalkerGroup
        GroupName: skywalker-group
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 8080
            ToPort: 8090
            CidrIp: 183.83.0.0/16
          -
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 183.83.0.0/16
