AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Repository:
    Type: String
    Description: GitHub Repository URL

  OauthToken:
    Type: String
    Description: GitHub Repository URL
    NoEcho: true

Resources:
  AmplifyApp:
    Type: "AWS::Amplify::App"
    Properties:
      Name: WelcomeApp
      Repository: !Ref Repository
      Description: WelcomeApp Example
      OauthToken: !Ref OauthToken
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            build:
              commands:
                - ls
          artifacts:
            baseDirectory: /serverless-app/app/
            files:
              - '*'
      Tags:
        - Key: Name
          Value: Todo
      IAMServiceRole: arn:aws:iam::749797989296:role/service-role/swastik

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain
